// Generated by Wrangler by running `wrangler types`

interface Env {
	FIREBASE_PROJECT_ID: string;
	FIREBASE_DATABASE_URL: string;
	FIREBASE_SERVICE_ACCOUNT_KEY: string;
	GEMINI_API_KEY: string;
	OPENROUTER_API_KEY: string;
	MISTRAL_API_KEY: string;
	AI: Ai;
}
