<template>
  <TransitionRoot appear :show="isOpen" as="template">
    <Dialog as="div" @close="closeModal" class="relative z-10">
      <TransitionChild
        as="template"
        enter="duration-300 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-200 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-black bg-opacity-75" />
      </TransitionChild>

      <div class="fixed inset-0 overflow-y-auto">
        <div
          class="flex min-h-full items-center justify-center p-4 text-center"
        >
          <TransitionChild
            as="template"
            enter="duration-300 ease-out"
            enter-from="opacity-0 scale-95"
            enter-to="opacity-100 scale-100"
            leave="duration-200 ease-in"
            leave-from="opacity-100 scale-100"
            leave-to="opacity-0 scale-95"
          >
            <DialogPanel
              class="w-full max-w-md transform overflow-hidden rounded-2xl bg-primary-900 dark:bg-primary-950 p-6 text-left align-middle shadow-xl transition-all border border-primary-700"
            >
              <DialogTitle
                as="h3"
                class="text-2xl font-semibold leading-6 text-primary-50 flex justify-between items-center"
              >
                {{
                  isEditing ? 'Edit Vocabulary Word' : 'Add New Vocabulary Word'
                }}
                <button
                  @click="closeModal"
                  class="text-primary-400 hover:text-primary-200 focus:outline-none"
                >
                  <svg
                    class="h-6 w-6"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M6 18L18 6M6 6l12 12"
                    ></path>
                  </svg>
                </button>
              </DialogTitle>
              <div class="mt-2">
                <p class="text-sm text-primary-300">
                  Add a new word to your personal vocabulary collection.
                </p>
              </div>

              <form @submit.prevent="addOrUpdateWord" class="mt-6 space-y-4">
                <div>
                  <label
                    for="term"
                    class="block text-sm font-medium text-primary-50 mb-1"
                  >
                    Word
                  </label>
                  <input
                    type="text"
                    id="term"
                    ref="wordInputRef"
                    v-model="termLowerCase"
                    placeholder="Enter the word"
                    @keydown.enter="handleEnterKey"
                    class="w-full px-3 py-2 border border-primary-700 rounded-md text-sm bg-primary-800 text-primary-50 placeholder-primary-400 focus:outline-none focus:ring-1 focus:ring-secondary-500 focus:border-secondary-500 transition-colors"
                    required
                  />
                  <button
                    type="button"
                    @click="autoGenerateDefinition"
                    :disabled="isGenerating || !formData.term.trim()"
                    class="mt-2 inline-flex items-center px-3 py-1 text-xs font-medium rounded-md bg-secondary-600 text-white hover:bg-secondary-700 focus:outline-none focus:ring-2 focus:ring-secondary-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    <svg
                      v-if="isGenerating"
                      class="animate-spin -ml-1 mr-2 h-4 w-4 text-white"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        class="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        stroke-width="4"
                      ></circle>
                      <path
                        class="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                    <svg
                      v-else
                      class="w-4 h-4 mr-1"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M13 10V3L4 14h7v7l9-11h-7z"
                      ></path>
                    </svg>
                    {{ isGenerating ? 'Generating...' : 'Auto-generate' }}
                  </button>
                </div>

                <div>
                  <label
                    for="meanings"
                    class="block text-sm font-medium text-primary-50 mb-1"
                  >
                    Meanings
                    <span class="text-primary-300 text-xs">
                      (Optional - will auto-generate if empty)
                    </span>
                  </label>
                  <textarea
                    id="meanings"
                    v-model="formData.meaningsText"
                    placeholder="Enter meanings separated by semicolons (;) or leave empty to auto-generate"
                    rows="5"
                    class="w-full px-3 py-2 border border-primary-700 rounded-md text-sm bg-primary-800 text-primary-50 placeholder-primary-400 focus:outline-none focus:ring-1 focus:ring-secondary-500 focus:border-secondary-500 transition-colors"
                  ></textarea>
                  <p class="text-xs text-primary-300 mt-1">
                    💡 Tip: Leave empty to automatically generate meanings
                  </p>
                </div>

                <div>
                  <label
                    for="examples"
                    class="block text-sm font-medium text-primary-50 mb-1"
                  >
                    Example Sentences
                    <span class="text-primary-300 text-xs">
                      (Optional - will auto-generate if empty)
                    </span>
                  </label>
                  <textarea
                    id="examples"
                    v-model="formData.examplesText"
                    placeholder="Enter example sentences separated by semicolons (;) or leave empty to auto-generate"
                    rows="5"
                    class="w-full px-3 py-2 border border-primary-700 rounded-md text-sm bg-primary-800 text-primary-50 placeholder-primary-400 focus:outline-none focus:ring-1 focus:ring-secondary-500 focus:border-secondary-500 transition-colors"
                  ></textarea>
                  <p class="text-xs text-primary-300 mt-1">
                    💡 Tip: Leave empty to auto-generate contextual examples
                  </p>
                </div>

                <div>
                  <label
                    for="categoryName"
                    class="block text-sm font-medium text-primary-50 mb-1"
                  >
                    Category Name
                  </label>

                  <!-- Category Selection Dropdown -->
                  <div v-if="!showNewCategoryInput">
                    <select
                      v-model="formData.categoryName"
                      @change="handleCategoryChange"
                      class="w-full px-3 py-2 border border-primary-700 rounded-md text-sm bg-primary-800 text-primary-50 focus:outline-none focus:ring-1 focus:ring-secondary-500 focus:border-secondary-500 transition-colors"
                      required
                    >
                      <option value="">Select a category</option>
                      <option
                        v-for="(category, id) in categories"
                        :key="id"
                        :value="category.name"
                      >
                        {{ category.name }}
                      </option>
                      <option value="__add_new__">+ Add New Category</option>
                    </select>
                  </div>

                  <!-- New Category Input -->
                  <div v-else class="space-y-2">
                    <input
                      type="text"
                      id="categoryName"
                      v-model="formData.categoryName"
                      placeholder="Enter new category name (e.g., Travel, Business, etc.)"
                      class="w-full px-3 py-2 border border-primary-700 rounded-md text-sm bg-primary-800 text-primary-50 placeholder-primary-400 focus:outline-none focus:ring-1 focus:ring-secondary-500 focus:border-secondary-500 transition-colors"
                      required
                      ref="categoryInputRef"
                    />
                    <div class="flex gap-2">
                      <button
                        type="button"
                        @click="confirmNewCategory"
                        class="inline-flex justify-center rounded-md border border-transparent bg-secondary-600 text-white px-3 py-1 text-xs font-medium hover:bg-secondary-700 focus:outline-none focus:ring-2 focus:ring-secondary-500 focus:ring-offset-2 transition-colors"
                      >
                        Confirm
                      </button>
                      <button
                        type="button"
                        @click="cancelNewCategory"
                        class="inline-flex justify-center rounded-md border border-transparent bg-primary-700 text-white px-3 py-1 text-xs font-medium hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 transition-colors"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>

                  <p class="text-xs text-primary-300 mt-1">
                    💡 Tip: Select existing category or add a new one
                  </p>
                </div>

                <div class="mt-6 flex justify-end space-x-3">
                  <button
                    type="button"
                    @click="closeModal"
                    class="inline-flex justify-center rounded-md border border-transparent bg-primary-700 px-4 py-2 text-sm font-medium text-primary-50 hover:bg-primary-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    class="inline-flex justify-center rounded-md border border-transparent bg-primary-50 text-primary-950 px-4 py-2 text-sm font-medium hover:bg-primary-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 transition-colors"
                  >
                    {{ isEditing ? 'Save Changes' : 'Add Word' }}
                  </button>
                </div>
              </form>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { computed, ref, watch, nextTick } from 'vue'
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  TransitionChild,
  TransitionRoot,
} from '@headlessui/vue'

import type { VocabularyWord } from '@/types'

const emit = defineEmits(['close', 'add-word', 'update-word', 'add-category'])

const initialFormData = {
  term: '',
  meaningsText: '',
  examplesText: '',
  categoryName: '',
}

const props = defineProps<{
  isOpen: boolean
  currentWord: VocabularyWord | null
  categories?: Record<string, { name: string }>
}>()

const formData = ref({ ...initialFormData })
const isGenerating = ref(false)
const wordInputRef = ref<HTMLInputElement>()
const categoryInputRef = ref<HTMLInputElement>()
const showNewCategoryInput = ref(false)

const isEditing = computed(() => !!props.currentWord)

// Computed property for term with automatic lowercase conversion
const termLowerCase = computed({
  get: () => formData.value.term,
  set: (value: string) => {
    formData.value.term = value.toLowerCase()
  }
})

// Watch for currentWord changes to handle form population/reset
watch(
  () => props.currentWord,
  (currentWordVal) => {
    if (currentWordVal) {
      // Populate formData with existing word data for editing
      formData.value.term = currentWordVal.term
      formData.value.meaningsText = currentWordVal.meanings
      formData.value.examplesText = currentWordVal.examples
      formData.value.categoryName = currentWordVal.categoryName
    } else if (props.isOpen) {
      // Reset formData for adding a new word (only when modal is open)
      Object.assign(formData.value, initialFormData)
    }
  }
)

// Watch for modal open state to handle focus and UI state
watch(
  () => props.isOpen,
  async (isOpenVal) => {
    if (!isOpenVal) {
      // Reset category input state when modal closes
      showNewCategoryInput.value = false
    } else {
      // Set focus on word input when modal opens
      await nextTick()
      wordInputRef.value?.focus()
    }
  }
)

function closeModal() {
  emit('close')
}

function handleCategoryChange(event: Event) {
  const target = event.target as HTMLSelectElement
  if (target.value === '__add_new__') {
    showNewCategoryInput.value = true
    formData.value.categoryName = ''
    // Focus the new category input after DOM update
    nextTick(() => {
      categoryInputRef.value?.focus()
    })
  }
}

function confirmNewCategory() {
  if (formData.value.categoryName.trim()) {
    // Emit event to notify parent to handle new category creation
    emit('add-category', formData.value.categoryName.trim())
    showNewCategoryInput.value = false
  }
}

function cancelNewCategory() {
  formData.value.categoryName = ''
  showNewCategoryInput.value = false
}

function handleEnterKey(event: KeyboardEvent) {
  event.preventDefault() // Prevent form submission
  event.stopPropagation() // Stop event bubbling
  autoGenerateDefinition() // Call the auto-generate function
}

async function autoGenerateDefinition() {
  if (formData.value.term.trim()) {
    isGenerating.value = true
    try {
      const { vocabularyWordsService } = await import('@/services/vocabularyService')
      const response = await vocabularyWordsService.explainWord(formData.value.term)
      const cleanedString = response.definition.replace(/```json\n|\n```/g, '')
      const parsedDefinition = JSON.parse(cleanedString)

      // Handle string values from the API response
      const meanings = parsedDefinition.definition || ''
      const examples = parsedDefinition.examples || ''

      // Convert semicolon-separated format to line breaks for better display
      formData.value.meaningsText = meanings.replace(/; /g, '\n')
      formData.value.examplesText = examples.replace(/; /g, '\n')
    } catch (error) {
      console.warn('Failed to auto-generate definition:', error)
      // Fallback: try to parse as simple definition and example
      try {
        const { vocabularyWordsService } = await import('@/services/vocabularyService')
        const response = await vocabularyWordsService.explainWord(formData.value.term)
        const cleanedString = response.definition.replace(/```json\n|\n```/g, '')
        const parsedDefinition = JSON.parse(cleanedString)

        // Handle legacy format
        formData.value.meaningsText = parsedDefinition.definition || ''
        formData.value.examplesText = parsedDefinition.example || ''
      } catch (fallbackError) {
        console.warn('Failed to auto-generate definition (fallback):', fallbackError)
      }
    } finally {
      isGenerating.value = false
    }
  }
}

function addOrUpdateWord() {
  if (isEditing.value && props.currentWord) {
    // Update existing word
    const updatedWord: VocabularyWord = {
      ...props.currentWord, // Keep existing categoryId
      term: formData.value.term,
      meanings: formData.value.meaningsText,
      examples: formData.value.examplesText,
      categoryName: formData.value.categoryName,
    }
    emit('update-word', updatedWord)
    closeModal()
  } else {
    // Add new word
    const wordToAdd: VocabularyWord = {
      term: formData.value.term,
      categoryId: '', // Will be set by the backend
      categoryName: formData.value.categoryName,
      meanings: formData.value.meaningsText,
      examples: formData.value.examplesText,
    }
    emit('add-word', wordToAdd)

    // Clean inputs immediately after creating a new word
    Object.assign(formData.value, initialFormData)
    showNewCategoryInput.value = false

    closeModal()
  }
}
</script>
